### ISSUE TITLE
Use swagger-api/swagger-parser for loading the schema

### ISSUE THREAD

**Issue by lispyclouds** [into-docker/clj-docker-client#42]
Using https://github.com/swagger-api/swagger-parser would keep us safer from changes, #ref tags and should handle OpenAPI 3.0 if and when it comes with minimal change.

Also there _may_ be some perf benefits in parsing.

**Comment by zerg000000** [comment]
Maybe we can do the same as `aws-api`, convert `spec` into `edn` and package them as separate jars?

If we did so, clj-docker-client could be faster ( by loading edn resources instead of yaml ) and lighter ( by reducing dependencies ).

Also, we prevent the potential licensing issues that might come from including the OpenAPI files.

**Comment by lispyclouds** [comment]
hello again @zerg000000 😄 

This is a great idea and should be explored soon! And as always any PRs would be swiftly merged!

This ties in well with #38 and would be a good solution to that too!

**Comment by lispyclouds** [comment]
being addressed in a simpler redesign: https://github.com/lispyclouds/contajners
